"""Tests for ansible_generator.py: verify generated Ansible project structure and content."""

from datetime import datetime
from jinja2 import Environment, FileSystemLoader
from src.utils.yaml_utils import save_yaml
from src.generator.ansible_generator import (apply_substitutions,
                                             render_j2,
                                             build_template_vars,
                                             copy_task_files,
                                             copy_bundled_files,
                                             generate)

def test_apply_substitutions_basic():
    """Placeholders are replaced with values from template_variables."""
    content = (
        "# __VERSION_NOTE__\n"
        "# Source: __SOURCE_HOSTNAME__\n"
        "# __TIMESTAMP__\n"
        "- name: Install packages\n"
        "  ansible.builtin.dnf:\n"
        "    name: \"{{ dnf_packages }}\"\n"
    )
    template_variables = {
        "version_note": "Generated by MigrateOS v0.1.0 from webserver.local",
        "source_hostname": "webserver.local",
        "timestamp": "2026-06-21T14:30:00",
    }

    result = apply_substitutions(content, template_variables)

    assert "__VERSION_NOTE__" not in result
    assert "__SOURCE_HOSTNAME__" not in result
    assert "__TIMESTAMP__" not in result
    assert "Generated by MigrateOS v0.1.0 from webserver.local" in result
    assert "webserver.local" in result
    assert "2026-06-21T14:30:00" in result
    # Ansible {{ }} syntax must survive untouched
    assert "{{ dnf_packages }}" in result

def test_apply_substitutions_missing_key():
    """Placeholders with missing keys are left untouched."""
    content = "# __VERSION_NOTE__\n# __SOURCE_HOSTNAME__\n"
    template_variables = {
        "version_note": "Generated by MigrateOS v0.1.0 from webserver.local",
        # source_hostname is missing
    }

    result = apply_substitutions(content, template_variables)

    assert "Generated by MigrateOS v0.1.0 from webserver.local" in result
    # Missing key — placeholder stays as-is
    assert "__SOURCE_HOSTNAME__" in result

def test_apply_substitutions_no_placeholders():
    """Content without placeholders passes through unchanged."""
    content = (
        "- name: Install packages\n"
        "  ansible.builtin.dnf:\n"
        "    name: \"{{ dnf_packages }}\"\n"
    )
    template_variables = {
        "version_note": "Generated by MigrateOS v0.1.0 from webserver.local",
        "source_hostname": "webserver.local",
        "timestamp": "2026-06-21T14:30:00",
    }

    result = apply_substitutions(content, template_variables)

    assert result == content

def test_render_j2_creates_file(tmp_path):
    """_render_j2 renders a .j2 template and writes the output to disk."""
    template_dir = tmp_path / "templates"
    template_dir.mkdir()
    (template_dir / "test.cfg.j2").write_text("# {{ version_note }}\nhost_key_checking = False\n")

    output_dir = tmp_path / "output"
    output_dir.mkdir()
    destination = output_dir / "test.cfg"

    jinja2_environment = Environment(loader=FileSystemLoader(str(template_dir)))
    template_variables = {"version_note": "Generated by MigrateOS v0.1.0"}

    render_j2(jinja2_environment, "test.cfg.j2", destination, template_variables)

    assert destination.exists()
    content = destination.read_text()
    assert "Generated by MigrateOS v0.1.0" in content
    assert "host_key_checking = False" in content

def test_render_j2_creates_parent_directories(tmp_path):
    """_render_j2 creates parent directories for the destination path if they don't exist."""
    template_dir = tmp_path / "templates"
    template_dir.mkdir()
    (template_dir / "nested.j2").write_text("content: {{ value }}\n")

    destination = tmp_path / "output" / "deep" / "nested" / "file.yml"

    jinja2_environment = Environment(loader=FileSystemLoader(str(template_dir)))
    template_variables = {"value": "hello"}

    render_j2(jinja2_environment, "nested.j2", destination, template_variables)

    assert destination.exists()
    assert "content: hello" in destination.read_text()

def test_render_j2_preserves_ansible_syntax(tmp_path):
    """_render_j2 does NOT interfere with Ansible {{ }} syntax inside templates.

    This is the critical invariant: Jinja2 renders its own {{ }} variables,
    but the template author must use {% raw %}...{% endraw %} blocks around
    Ansible variable references. This test verifies that pattern works.
    """
    template_dir = tmp_path / "templates"
    template_dir.mkdir()
    (template_dir / "task.yml.j2").write_text(
        "# {{ version_note }}\n"
        "- name: Install packages\n"
        "  ansible.builtin.dnf:\n"
        '    name: "{{ dnf_packages }}"\n'
    )

    destination = tmp_path / "output" / "task.yml"

    jinja2_environment = Environment(
        loader=FileSystemLoader(str(template_dir)),
        # Use Jinja2 block_start/block_end that don't conflict with Ansible
        # OR the template uses {% raw %} blocks.
        # For this test, we pass dnf_packages as a variable so Jinja2 resolves it.
    )
    template_variables = {
        "version_note": "Generated by MigrateOS v0.1.0",
        "dnf_packages": "nginx, postgresql",
    }

    render_j2(jinja2_environment, "task.yml.j2", destination, template_variables)

    content = destination.read_text()
    assert "Generated by MigrateOS v0.1.0" in content
    assert "nginx, postgresql" in content

def test_build_template_vars_direct_passthroughs():
    """OS facts are passed through with renamed keys."""
    manifest = {
        "os_facts": {
            "os": "fedora",
            "version": "41",
            "hostname": "webserver.local",
            "kernel": "6.11.4-201.fc41.x86_64",
            "architecture": "x86_64",
            "timezone": "America/New_York",
            "locale": "en_US.UTF-8",
            "selinux": {
                "status": "enabled",
                "mode": "enforcing",
            },
        },
    }

    result = build_template_vars(manifest)

    assert result["source_os"] == "fedora"
    assert result["source_version"] == "41"
    assert result["source_hostname"] == "webserver.local"
    assert result["source_kernel"] == "6.11.4-201.fc41.x86_64"
    assert result["source_architecture"] == "x86_64"
    assert result["source_timezone"] == "America/New_York"
    assert result["source_locale"] == "en_US.UTF-8"
    assert result["selinux_status"] == "enabled"
    assert result["selinux_mode"] == "enforcing"

def test_build_template_vars_service_tier_split():
    """Services are split into infrastructure and application tiers."""
    manifest = {
        "services": {
            "services": [
                {"name": "postgresql.service", "service_tier": "infrastructure"},
                {"name": "nginx.service", "service_tier": "infrastructure"},
                {"name": "myapp.service", "service_tier": "application"},
            ],
        },
    }

    result = build_template_vars(manifest)

    assert len(result["services_infra"]) == 2
    assert len(result["services_app"]) == 1
    assert result["services_infra"][0]["name"] == "postgresql.service"
    assert result["services_app"][0]["name"] == "myapp.service"

def test_build_template_vars_config_split():
    """Config entries are split into single files and directories."""
    manifest = {
        "configs": {
            "config_files": [
                {"path": "/etc/nginx/nginx.conf", "copy_method": "file"},
                {"path": "/etc/ssh/sshd_config.d", "copy_method": "directory"},
                {"path": "/etc/redis.conf", "copy_method": "file"},
            ],
            "warnings": [],
            "secrets_required": [],
        },
    }

    result = build_template_vars(manifest)

    assert len(result["config_files"]) == 2
    assert len(result["config_dirs"]) == 1
    assert result["config_dirs"][0]["path"] == "/etc/ssh/sshd_config.d"

def test_build_template_vars_dnf_groups_prefixed():
    """DNF group names are prefixed with @."""
    manifest = {
        "packages": {
            "packages": [],
            "groups": ["Development Tools", "Sound and Video"],
            "extras": [],
            "custom_repos": [],
        },
    }

    result = build_template_vars(manifest)

    assert result["dnf_groups"] == ["@Development Tools", "@Sound and Video"]

def test_build_template_vars_custom_repo_files_extracted():
    """Custom repo filenames are extracted and .repo suffix is stripped."""
    manifest = {
        "packages": {
            "packages": [],
            "groups": [],
            "extras": [],
            "custom_repos": [
                {"filename": "rpmfusion-free.repo", "content": "[rpmfusion-free]\n..."},
                {"filename": "docker-ce.repo", "content": "[docker-ce]\n..."},
            ],
        },
    }

    result = build_template_vars(manifest)

    assert result["custom_repo_files"] == ["rpmfusion-free", "docker-ce"]

def test_build_template_vars_computed_booleans_all_false():
    """Computed booleans are False when manifest sections are empty."""
    manifest = {
        "services": {"services": []},
        "cron": {"files": [], "timers": []},
        "sysctl": {"files": []},
        "containers": {"running_containers": []},
        "packages": {"custom_repos": []},
        "configs": {"secrets_required": []},
        "network": {"connections": [], "warning": None},
        "selinux": {"custom_modules": []},
    }

    result = build_template_vars(manifest)

    assert result["has_cron"] is False
    assert result["has_sysctl"] is False
    assert result["has_containers"] is False
    assert result["has_custom_repos"] is False
    assert result["has_custom_units"] is False
    assert result["has_secrets"] is False
    assert result["has_databases"] is False
    assert result["has_network"] is False
    assert result["has_custom_selinux"] is False

def test_build_template_vars_has_databases_true():
    """has_databases is True when a known database service is present."""
    manifest = {
        "services": {
            "services": [
                {"name": "postgresql.service", "service_tier": "infrastructure"},
            ],
        },
    }

    result = build_template_vars(manifest)

    assert result["has_databases"] is True

def test_build_template_vars_has_databases_false():
    """has_databases is False when no database services are present."""
    manifest = {
        "services": {
            "services": [
                {"name": "nginx.service", "service_tier": "infrastructure"},
            ],
        },
    }

    result = build_template_vars(manifest)

    assert result["has_databases"] is False

def test_build_template_vars_version_note_and_timestamp():
    """Version note contains the source hostname; timestamp is valid ISO."""
    manifest = {
        "os_facts": {
            "os": "fedora",
            "version": "41",
            "hostname": "dbserver.local",
            "kernel": "6.11.4",
            "architecture": "x86_64",
            "timezone": "UTC",
            "locale": "C",
            "selinux": {"status": "enabled", "mode": "enforcing"},
        },
    }

    result = build_template_vars(manifest)

    assert "dbserver.local" in result["version_note"]
    assert "MigrateOS" in result["version_note"]
    # timestamp should be parseable ISO format
    datetime.fromisoformat(result["timestamp"])

def test_copy_task_files_creates_all_files(tmp_path):
    """copy_task_files reads template .yml files, applies substitutions, writes to dest."""

    template_dir = tmp_path / "templates" / "tasks"
    template_dir.mkdir(parents=True)
    tasks_dest = tmp_path / "output" / "roles" / "migrated_server" / "tasks"

    # Create 3 stub task files (subset of 15 for speed)
    (template_dir / "bootstrap.yml").write_text(
        "# __VERSION_NOTE__\n- name: Bootstrap\n  ansible.builtin.raw: echo ok\n"
    )
    (template_dir / "packages.yml").write_text(
        "# __VERSION_NOTE__\n- name: Install packages\n  ansible.builtin.dnf:\n    name: \"{{ dnf_packages }}\"\n"
    )
    (template_dir / "main.yml").write_text(
        "# __VERSION_NOTE__\n- name: Import tasks\n  ansible.builtin.import_tasks: bootstrap.yml\n"
    )

    template_variables = {
        "version_note": "Generated by MigrateOS v0.1.0 from webserver.local",
        "source_hostname": "webserver.local",
        "timestamp": "2026-06-21T14:30:00",
    }

    # Patch TASK_FILE_NAMES to only include our 3 stubs
    import src.generator.ansible_generator as gen
    original_names = gen.TASK_FILE_NAMES
    gen.TASK_FILE_NAMES = ["bootstrap.yml", "packages.yml", "main.yml"]
    try:
        copy_task_files(template_variables, template_dir, tasks_dest)
    finally:
        gen.TASK_FILE_NAMES = original_names

    assert (tasks_dest / "bootstrap.yml").exists()
    assert (tasks_dest / "packages.yml").exists()
    assert (tasks_dest / "main.yml").exists()

    content = (tasks_dest / "bootstrap.yml").read_text()
    assert "__VERSION_NOTE__" not in content
    assert "Generated by MigrateOS v0.1.0 from webserver.local" in content

def test_copy_task_files_creates_handlers(tmp_path):
    """copy_task_files creates handlers/main.yml in the output."""

    template_dir = tmp_path / "templates" / "tasks"
    template_dir.mkdir(parents=True)
    handler_dir = template_dir / "handlers"
    handler_dir.mkdir()
    tasks_dest = tmp_path / "output" / "roles" / "migrated_server" / "tasks"

    # Create minimal stubs so the loop doesn't fail
    (template_dir / "bootstrap.yml").write_text("# __VERSION_NOTE__\n- name: test\n")
    (template_dir / "main.yml").write_text("# __VERSION_NOTE__\n- name: test\n")
    (handler_dir / "main.yml").write_text(
        "# __VERSION_NOTE__\n- name: restart service\n  ansible.builtin.systemd:\n    state: restarted\n"
    )

    template_variables = {
        "version_note": "Generated by MigrateOS v0.1.0",
        "source_hostname": "webserver.local",
        "timestamp": "2026-06-21T14:30:00",
    }

    import src.generator.ansible_generator as gen
    original_names = gen.TASK_FILE_NAMES
    gen.TASK_FILE_NAMES = ["bootstrap.yml", "main.yml"]
    try:
        copy_task_files(template_variables, template_dir, tasks_dest)
    finally:
        gen.TASK_FILE_NAMES = original_names

    handler_output = tasks_dest / "handlers" / "main.yml"
    assert handler_output.exists()
    content = handler_output.read_text()
    assert "restart service" in content
    assert "__VERSION_NOTE__" not in content

def test_copy_task_files_preserves_ansible_syntax(tmp_path):
    """Ansible {{ }} variable references survive copy_task_files untouched."""

    template_dir = tmp_path / "templates" / "tasks"
    template_dir.mkdir(parents=True)
    tasks_dest = tmp_path / "output" / "roles" / "migrated_server" / "tasks"

    (template_dir / "packages.yml").write_text(
        "# __VERSION_NOTE__\n"
        "- name: Install packages\n"
        "  ansible.builtin.dnf:\n"
        '    name: "{{ dnf_packages }}"\n'
    )

    template_variables = {
        "version_note": "Generated by MigrateOS v0.1.0",
        "source_hostname": "webserver.local",
        "timestamp": "2026-06-21T14:30:00",
    }

    import src.generator.ansible_generator as gen
    original_names = gen.TASK_FILE_NAMES
    gen.TASK_FILE_NAMES = ["packages.yml"]
    try:
        copy_task_files(template_variables, template_dir, tasks_dest)
    finally:
        gen.TASK_FILE_NAMES = original_names

    content = (tasks_dest / "packages.yml").read_text()
    assert '{{ dnf_packages }}' in content
    assert "__VERSION_NOTE__" not in content

def test_copy_bundled_files_copies_tree(tmp_path):
    """copy_bundled_files copies output_dir/files/ into the Ansible role."""

    output_dir = tmp_path / "bundler_output"
    (output_dir / "files" / "etc" / "nginx").mkdir(parents=True)
    (output_dir / "files" / "etc" / "nginx" / "nginx.conf").write_text("server {}\n")
    (output_dir / "files" / "systemd").mkdir(parents=True)
    (output_dir / "files" / "systemd" / "myapp.service").write_text("[Unit]\nDescription=myapp\n")

    ansible_dir = tmp_path / "generated-ansible"
    ansible_dir.mkdir()

    copy_bundled_files(output_dir, ansible_dir)

    assert (ansible_dir / "roles" / "migrated_server" / "files" / "etc" / "nginx" / "nginx.conf").exists()
    assert (ansible_dir / "roles" / "migrated_server" / "files" / "systemd" / "myapp.service").exists()
    assert (ansible_dir / "roles" / "migrated_server" / "files" / "etc" / "nginx" / "nginx.conf").read_text() == "server {}\n"


def test_copy_bundled_files_noop_when_no_files(tmp_path):
    """copy_bundled_files does nothing when output_dir/files/ doesn't exist."""

    output_dir = tmp_path / "bundler_output"
    output_dir.mkdir()

    ansible_dir = tmp_path / "generated-ansible"
    ansible_dir.mkdir()

    copy_bundled_files(output_dir, ansible_dir)

    # No files/ dir in output, so nothing copied
    assert not (ansible_dir / "roles" / "migrated_server" / "files").exists()

def test_generate_creates_full_structure(tmp_path, sample_manifest):
    """generate() creates all expected files and directories from a manifest."""
    manifest_path = tmp_path / "manifest.yml"
    save_yaml(sample_manifest, manifest_path)

    output_dir = tmp_path / "output"
    output_dir.mkdir()

    generate(manifest_path, output_dir)

    ansible_dir = output_dir / "generated-ansible"

    # Root files
    assert (ansible_dir / "ansible.cfg").exists()
    assert (ansible_dir / "requirements.yml").exists()
    assert (ansible_dir / "inventory.ini").exists()
    assert (ansible_dir / "site.yml").exists()
    assert (ansible_dir / "WARNINGS.md").exists()

    # Group vars
    assert (ansible_dir / "group_vars" / "new_server.yml").exists()
    assert (ansible_dir / "group_vars" / "vault.example.yml").exists()

    # Task files
    tasks_dir = ansible_dir / "roles" / "migrated_server" / "tasks"
    assert (tasks_dir / "main.yml").exists()
    assert (tasks_dir / "bootstrap.yml").exists()
    assert (tasks_dir / "packages.yml").exists()

    # Handlers
    assert (tasks_dir / "handlers" / "main.yml").exists()


def test_generate_inventory_has_change_me(tmp_path, sample_manifest):
    sample_manifest["services"]["services"] = []
    manifest_path = tmp_path / "manifest.yml"
    save_yaml(sample_manifest, manifest_path)

    output_dir = tmp_path / "output"
    output_dir.mkdir()

    generate(manifest_path, output_dir)

    inventory = (output_dir / "generated-ansible" / "inventory.ini").read_text()
    assert "ansible_host=CHANGE_ME" in inventory
    assert "webserver.local" in inventory


def test_generate_site_yml_references_role(tmp_path, sample_manifest):
    sample_manifest["services"]["services"] = []
    manifest_path = tmp_path / "manifest.yml"
    save_yaml(sample_manifest, manifest_path)

    output_dir = tmp_path / "output"
    output_dir.mkdir()

    generate(manifest_path, output_dir)

    site_yml = (output_dir / "generated-ansible" / "site.yml").read_text()
    assert "migrated_server" in site_yml